apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: ai-platform
spec:
  type: ClusterIP
  selector:
    app: streamlit-ui
  ports:
    - name: http
      port: 80
      targetPort: 8501
